name: catalog-sync-dev

services:
  mongodb:
    image: mongo:7.0
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: catalog
    networks:
      - ring

  crud-service:
    image: ghcr.io/mia-platform/crud-service
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/catalog
      - COLLECTION_DEFINITION_FOLDER=/home/node/app/collections
      - USER_ID_HEADER_KEY=userid
    volumes:
      - ./crud-service:/home/node/app/collections
    networks:
      - ring

  # files-service:
  #   image: nexus.mia-platform.eu/plugins/files-service
  #   ports:
  #     - '3000:3000'
  #   environment:
  #     - CONFIG_FILE_PATH=/home/node/app/configs/config.json
  #     - CRUD_URL=http://crud-service:3000/files/
  #     - HEADERS_TO_PROXY=userid
  #     - PATH_PREFIX=/files/
  #   volumes:
  #     - ./files-service:/home/node/app/configs
  #   extra_hosts:
  #     - host.docker.internal:host-gateway
  #   networks:
  #     - ring

networks:
  ring:
