name: Linting

on:
  workflow_call:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          show-progress: false

      - name: Setup Node.js
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version-file: .nvmrc
          check-latest: true
          cache: yarn

      - name: Install Dependencies
        run: yarn install --immutable
        
      - name: Check Linting
        run: yarn lint

      - name: Use golang 1.20
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version: '1.20'
      - name: Install addlicense
        run: go install github.com/google/addlicense@latest
      - name: Check license
        run: yarn check-license
